In [2]:
#Q1
import numpy as np
a=np.array([(1, 2), (3, 4)])
a.tolist()
print(a)

[[1 2]
 [3 4]]


In [3]:

#Q2
import numpy as np
a=np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b)
c = np.trace(b)
print(c)

[[1 2 3]
 [4 5 6]]
6


In [4]:
#Q4
import numpy as np
list1=np.array([[1,2],[3,4]])
list2=np.array([[5,6],[7,8]])
c=np.add(list1,list2)
print(c)

[[ 6  8]
 [10 12]]


In [7]:
#Q5
import numpy as np
x =np.array([[1,2],[3,4]])
print(x)
y =x.mean(axis=1)
z= x-y
print(z)

[[1 2]
 [3 4]]
[[-0.5 -1.5]
 [ 1.5  0.5]]
